export const STATE_0_IDLE = 'STATE_0_IDLE'
export const STATE_1_UPLOADING = 'STATE_1_UPLOADING'

export const STATE_2_UPLOADED= 'STATE_2_UPLOADED'

export const STATE_3_PROCESSING = 'STATE_3_PROCESSING'
export const STATE_4_PROCESSED = 'STATE_4_PROCESSED'
export const STATE_5_DOWNLOADING = 'STATE_5_DOWNLOADING'
export const STATE_6_DOWNLOADED = 'STATE_6_DOWNLOADED'
export const STATE_99_ERROR = 'STATE_99_ERROR'